# Generated by Django 5.2.7 on 2025-10-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Администратор"),
                    ("TEACHER", "Преподаватель"),
                    ("STUDENT", "Студент"),
                    ("STUPID", "Тупица"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
